name: Build for windows
on:
  workflow_call:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - chore/*
      - security/*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-windows:
    name: Build windows binaries
    strategy:
      matrix:
        include:
          - { sys: vcvars64, env: x86_64, runner: windows-2022 }
          - { sys: vcvars32, env: i686, runner: windows-2022 }
          - { sys: vcvarsarm64, env: arm64, runner: windows-11-arm }
    runs-on: ${{ matrix.runner }}
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install NASM
        shell: cmd
        run: choco install nasm -y

      - name: Install Ninja for Win-ARM64
        shell: pwsh
        if: matrix.runner == 'windows-11-arm'
        run: |
          Invoke-WebRequest https://github.com/ninja-build/ninja/releases/download/v1.13.1/ninja-winarm64.zip -OutFile ninja-winarm64.zip
          Expand-Archive ninja-winarm64.zip -DestinationPath ninja
          Copy-Item ninja\ninja.exe -Destination "C:\Windows\System32"

      # - name: Setup tmate session for debugging
      #   uses: mxschmitt/action-tmate@v3

      - name: Build
        shell: cmd
        run: ./win/build.bat ${{ matrix.sys }}

      - name: Build tarballs
        shell: bash
        run: |
          set -euo pipefail
          suffix="${{ matrix.env }}-win32"
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            ver="${{ github.head_ref || github.ref_name }}"
            curl_tar="curl-impersonate-${ver}.${suffix}.tar.gz"
            lib_tar="libcurl-impersonate-${ver}.${suffix}.tar.gz"
          else
            curl_tar="curl-impersonate-${suffix}.tar.gz"
            lib_tar="libcurl-impersonate-${suffix}.tar.gz"
          fi
          tar -czf "$curl_tar" -C packages/bin .
          tar -czf "$lib_tar"  -C packages lib include

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts.windows.${{ matrix.env }}
          path: |
            ./curl-impersonate*.tar.gz
            ./libcurl-impersonate*.tar.gz
